[package]
name = "rust-invaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dev = ["bevy/dynamic"]

[dependencies]
bevy = "0.8.0"
rand = "0.8.5"

[workspace]
resolver = "2"
